version: '3'
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
    restart: always

  api:
    restart: always  
    build:
      dockerfile: Dockerfile
      context: ./API
    volumes: 
      - /app/node_modules
      - ./API:/app
    network_mode: host

  app:
    build:
      dockerfile: Dockerfile
      context: ./my-react-app
    volumes:
      - /app/node_modules
      - ./my-react-app:/app
      - ./my-react-app/nginx:/etc/nginx/conf.d
    network_mode: host
